config/routes.rb
ArrisTool::Application.routes.draw do
  resources :arris_headends

	match '/report', to: 'cmts#report', via: 'get'
	match '/sweep', to: 'cmts#sweep', via: 'get'
  match '/managec3' => 'cmts#managec3', via: 'get'
	match '/showcablemodems' => 'cmts#scm', via: 'get'
  match '/scmsum' => 'cmts#scmsum', via: 'get'
	match '/scmdetail' => 'cmts#scmdetail', via: 'get'
  match '/schdetail' => 'cmts#schdetail', via: 'get'
  match '/hostmaclookup' => 'cmts#hostmaclookup', via: 'get'
  match '/showrun' => 'cmts#showrun', via: 'get'
  match '/showflaplist' => 'cmts#showflaplist', via: 'get'
	match '/showcontrollers' => 'cmts#showcontrollers', via: 'get'
  match '/showenvironment' => 'cmts#showenvironment', via: 'get'
  match '/deleteoffline' => 'cmts#deleteoffline', via: 'get'
  match '/resetmodemcounters' => 'cmts#resetmodemcounters', via: 'get'
  match '/clearflaplist' => 'cmts#clearflaplist', via: 'get'
  match '/plat' => 'cmts#showplatinfo', via: 'get'

  resources :cmts

  root :to => 'cmts#index'

end

app/controllers/cmts_controller.rb
require 'snmp4em'
require 'google_chart'

class CmtsController < ApplicationController
  include ApplicationHelper
#  before_action :set_cmt, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate

  def initialize
    @report = []
    $sweep_cache = nil

    cacti = "0.0.0.0"

    graph_link = "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=_graph_id_&rra_id=1"

    @ds_util_graph_map = {'cmts1.mm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6519&rra_id=0&view_type=tree",
                          'cmts2.mm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6522&rra_id=0&view_type=tree",
                          'cmts3.mm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6525&rra_id=0&view_type=tree",
                          'cmts4.mm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6527&rra_id=0&view_type=tree",
                          'cmts5.mm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6528&rra_id=0&view_type=tree",
													'cmts1.tbm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6517&rra_id=0&view_type=tree",
													'cmts2.tbm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6524&rra_id=0&view_type=tree",
                          'cmts3.tbm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6526&rra_id=0&view_type=tree",
                          'cmts4.tbm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6865&rra_id=0&view_type=tree",
                          'cmts1.sqpk' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6520&rra_id=0&view_type=tree",
                          'cmts2.sqpk' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6523&rra_id=0&view_type=tree",
                          'cmts3.sqpk' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=6905&rra_id=1&view_type",
													'cmts1.twm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6521&rra_id=0&view_type=tree",
                          'cmts1.bwm' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6518&rra_id=0&view_type=tree"}

    @ds_bandwidth_graph_map = {'cmts1.mm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=5472&rra_id=1&view_type=",
                               'cmts2.mm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=5480&rra_id=1&view_type=",
                               'cmts3.mm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=5487&rra_id=1&view_type=",
                               'cmts4.mm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=6735&rra_id=1&view_type=",
                               'cmts5.mm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=6606&rra_id=1&view_type=",
                               'cmts1.tbm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=5463&rra_id=1&view_type=",
                               'cmts2.tbm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=5462&rra_id=1&view_type=",
                               'cmts3.tbm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=6800&rra_id=1&view_type=",
		                           'cmts4.tbm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=6855&rra_id=1&view_type=",
                               'cmts1.sqpk' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=5495&rra_id=1&view_type=",
                               'cmts2.sqpk' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=6801&rra_id=1&view_type=",
															 'cmts3.sqpk' => "http://#{cacti}/cacti/graph_image.php?local_graph_id=6898&rra_id=0&view_type=tree",
                               'cmts1.twm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=6793&rra_id=1&view_type=",
                               'cmts1.bwm' => "http://#{cacti}/cacti/graph.php?action=zoom&local_graph_id=6379&rra_id=1&view_type="
                              }

    # Provisioned CPE History
    cpe_graphids = {'cmts1.bwm' => 6378,
                    'cmts1.mm' => 5471, 'cmts2.mm' => 5479, 'cmts3.mm' => 5502, 'cmts4.mm' => 6200, 'cmts5.mm' => 6312, 'cmts6.mm' => 1131, 'cmts7.mm' => 1143, 'cmts8.mm' => 1155,
                    'cmts1.tbm' => 5470, 'cmts2.tbm' => 5506, 'cmts3.tbm' => 6290, 'cmts4.tbm' => 6864,
                    'cmts1.sqpk' => 5494, 'cmts2.sqpk' => 6185, 'cmts3.sqpk' => 6897,
                    'cmts1.twm' => 6263
                    }

    @cpe_graph_map = {}
    cpe_graphids.each do |k,v|
      @cpe_graph_map[k] = graph_link.gsub(/_graph_id_/,v.to_s)
    end

    # MER History
    mer_graphids = {'cmts1.bwm' => 6377,
                    'cmts1.mm' => 5511, 'cmts2.mm' => 5513, 'cmts3.mm' => 5515, 'cmts4.mm' => 6199, 'cmts5.mm' => 6311,
                    'cmts1.tbm' => 5512, 'cmts2.tbm' => 5514, 'cmts3.tbm' => 6289, 'cmts4.tbm' => 6863,
                    'cmts1.sqpk' => 5510, 'cmts2.sqpk' => 6184, 'cmts3.sqpk' => 6896,
                    'cmts1.twm' => 6279}
    @mer_graph_map = {}
    mer_graphids.each do |k,v|
      @mer_graph_map[k] = graph_link.gsub(/_graph_id_/,v.to_s)
    end
  end

  # GET /cmts
  # GET /cmts.json
  def index
    @cmts = ArrisHeadend.all # Cmt.all
    render :layout => "application"
  end

  # GET /cmts/1
  # GET /cmts/1.json
  def show
    @cmt = ArrisHeadend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cmt }
    end
  end

  def managec3
    @c3Config = Cmt.getC3Config(params)
    respond_to do |format|
      format.html { render :managec3, :layout => "application" }
    end
  end

  #
  # Sweep modems for stats
  #
	def sweep
    # Call sweep method
		@sweep_data, @ds, @us = Cmt.sweep(params)

    if (!@sweep_data)
      respond_to do |format|
        format.html { render :sweep_failed, :layout => "application" }
      end
    else
      GoogleChart::PieChart.new('340x220', "",false) do |pc|
        pc.data "16+", @ds['16plus'].round(0)
        pc.data "-15 to +15", @ds['-15to+15'].round(0)
        pc.data "-14 or less", @ds['-14less'].round(0)
        @ds_chart = pc.to_url
      end

      GoogleChart::PieChart.new('340x220', "",false) do |pc|
        pc.data "51 to 61", @us['51to61'].round(0)
        pc.data "34 to 51", @us['51to35'].round(0)
        pc.data "34 or less", @us['34less'].round(0)
        @us_chart = pc.to_url
      end

      # Set host and channel headers
  		@sweep_host = params[:target].upcase!
      @sweep_channel = "All Channels" if !params[:channel]
      @sweep_channel = "Channel #{params[:channel].to_i + 1}" if params[:channel]

      ModemSweepCache.new.update(@sweep_data)

      respond_to do |format|
          format.html { render :sweep, :layout => "application" }
      end
    end
	end

  def report
    @cmts = ArrisHeadend.order(name: :asc)

    # Debug
    # ld("Retrieving CMTS list")
    # ld(@cmts)
    # ld(sprintf("%-30s %-30s", "Got C3 list..",Time.now))
    # ld("Got C3 list.. #{Time.now}")
    # ld("Quering C3 Stats.. #{Time.now}")
    # ld(sprintf("%-30s %-30s", "Quering C3 Stats..",Time.now))
    # @cmts.each do |cmts|
    getCMTSChannelCounts()
    # ld("Got C3 Stats.. #{Time.now}")
    # ld(sprintf("%-30s %-30s", "Got C3 Stats..",Time.now))
    # end

    sitemap = {'bwm' => 'Bill Williams', 'mm' => 'Mingus Mt.', 'tbm' => 'Table Mt.', 'sqpk' => 'Squaw Peak', 'twm' => 'Towers Mt.'}
    allsites = 0
    @report.each do |cmts|
      @totals = {} if !@totals

      re = /\w*\d+\.(.*)/
      m = cmts[:host].match re
      site = m[1]
      @totals[sitemap[site]] = 0 if !@totals[sitemap[site]]
      @totals[sitemap[site]] += cmts[:totalsubs]
      allsites += cmts[:totalsubs]
    end
    @totals.merge!({'All Sites' => allsites})
    # ld("Rendering C3 Stats HTML.. #{Time.now}")
    # ld(sprintf("%-30s %-30s", "Rendering C3 Stats HTML..",Time.now))
    # ld(@report)
    respond_to do |format|
        format.html { render :report, :layout => "application" }
    end
  end

  def getCMTSChannelCounts(cmts = nil)

    community = 'broadbandcactus'

    us_interface_state = '1.3.6.1.2.1.2.2.1.8'

    us_registered_sms  = '1.3.6.1.4.1.4115.1.4.3.1.1.1.1.6'
    us_snr             = '1.3.6.1.4.1.4115.1.4.3.6.1.3.1.21'
    us_freq            = '1.3.6.1.2.1.10.127.1.1.2.1.2'
    ch_width           = '1.3.6.1.2.1.10.127.1.1.2.1.3'
    mer                = '1.3.6.1.2.1.10.127.1.1.4.1.5'
    us_channel_type    = '1.3.6.1.2.1.10.127.1.1.2.1.15'
    us_modulation_prof = '1.3.6.1.2.1.10.127.1.1.2.1.4'
		us_util						 = '1.3.6.1.2.1.10.127.1.3.9.1.3'

		ds_util	           = SNMP::ObjectId.new('1.3.6.1.2.1.10.127.1.3.9.1.3.4.128.1')
    ds_modulation      = SNMP::ObjectId.new('1.3.6.1.2.1.10.127.1.1.1.1.4.4')

    ch1_int_state = SNMP::ObjectId.new("#{us_interface_state}.5")
    ch2_int_state = SNMP::ObjectId.new("#{us_interface_state}.6")
    ch3_int_state = SNMP::ObjectId.new("#{us_interface_state}.7")
    ch4_int_state = SNMP::ObjectId.new("#{us_interface_state}.8")
    ch5_int_state = SNMP::ObjectId.new("#{us_interface_state}.9")
    ch6_int_state = SNMP::ObjectId.new("#{us_interface_state}.10")

    ch1_sub_int_state = SNMP::ObjectId.new("#{us_interface_state}.11")
    ch2_sub_int_state = SNMP::ObjectId.new("#{us_interface_state}.12")
    ch3_sub_int_state = SNMP::ObjectId.new("#{us_interface_state}.13")
    ch4_sub_int_state = SNMP::ObjectId.new("#{us_interface_state}.14")
    ch5_sub_int_state = SNMP::ObjectId.new("#{us_interface_state}.15")
    ch6_sub_int_state = SNMP::ObjectId.new("#{us_interface_state}.16")

    ch1 = SNMP::ObjectId.new("#{us_registered_sms}.11")
    ch2 = SNMP::ObjectId.new("#{us_registered_sms}.12")
    ch3 = SNMP::ObjectId.new("#{us_registered_sms}.13")
    ch4 = SNMP::ObjectId.new("#{us_registered_sms}.14")
    ch5 = SNMP::ObjectId.new("#{us_registered_sms}.15")
    ch6 = SNMP::ObjectId.new("#{us_registered_sms}.16")

    ch1_freq = SNMP::ObjectId.new("#{us_freq}.11")

app/helpers/cmts_helper.rb
module CmtsHelper

  # Extend Array Class
  class Array
    def sum
      inject(0.0) { |result, el| result + el }
    end

    def mean 
      sum / size
    end
  end

  #
  # Avg upstream utilization
  # Receives: Complex hash of CMTS stats
  # Returns : Returns float
  #
  def avg_us_util(cmts)
    a = []
    cmts.each do |k,v|
      next if k == :int_state && v != 'UP'
      next if ![1,2,3,4,5].include?(k)
      v.each do |kk,vv|
        next if kk != :util
        a.push(vv.to_f)
      end
    end
    r = a.inject(0.0) { |sum, el| sum + el } / a.size
  end

  #
  # Help determine length of Flap List display to avoid displaying
  # Footer breadcrumb if nothing displaying or a short list
  #
  # Receives: Hash
  # Returns : true/false
  #
  def extendedFlapList(list)

    length = 0
    if (list.class == {}.class)
      list.each do |k,v|
        length += 1
        if (v.class == [].class)
          length += v.length
        end
      end
    end
    return true if length > 20
    return false    
  end

  # -------------------------------------------------------------------------------
  #
  # Formatted Data Usage Calulator for View
  #
  # - Can return results formated with string (bits,Bytes,MB,TB, etc.)
  # -------------------------------------------------------------------------------
  def formatBytes(bytes)
  	return 0 if (bytes.nil? || bytes.to_i == 0)

    bytes = bytes.to_f

    data_used = Hash.new()

    data_used[:B] = 0
    data_used[:kb] = 0
    data_used[:mb] = 0
    data_used[:gb] = 0
    data_used[:tb] = 0

    data_used[:b]  = bytes.to_i * 10
    data_used[:B]  = bytes
    data_used[:kb] = data_used[:B].to_f / 1000
    data_used[:mb] = data_used[:kb].to_f / 1000
    data_used[:gb] = data_used[:mb].to_f / 1000
    data_used[:tb] = data_used[:gb].to_f / 1000

    if (data_used[:tb] > 1)
    	return "#{data_used[:tb].round(2)}TB"
    elsif (data_used[:gb] > 1)
    	return "#{data_used[:gb].round(2)}GB"
    elsif (data_used[:mb] > 1)
    	return "#{data_used[:mb].round(2)}MB"
    elsif (data_used[:kb] > 1)
    	return "#{data_used[:kb].round(2)}KB"
    elsif (data_used[:B] > 1)
    	return "#{data_used[:B].round(2)}"
    elsif (data_used[:b] > 1)
    	return "#{data_used[:b].round(2)}bits"
    end
  end

  #
  # Check mac prefix against list of known DOCSIS v2 modems on CommSpeed's system
  #
  # Receives: MAC address
  # Returns : true/false
  #
  def sanctionedModem(mac)
    # ld("method: sanctionedModem(#{mac})")

    _mac = formatMac(mac,2,":")

    validMac = ['00:0e:9b','00:19:7d','00:19:7e','00:14:a4','00:16:ce','00:16:cf','00:1f:e1','00:1f:e2','00:22:69','78:e4:00','c0:cb:38','f0:7b:cb','00:1e:4c','00:1f:3a','00:1d:d9', '90:6e:bb']
    return true if validMac.include?(_mac[0,8])
    return false
  end

  #
  # Format zipcode
  #
  # Receives: String
  # Returns : String (formated)
  #
  def formatZipCode(zip,delimiter="-")
    re = /([0-9]{5})/

    # Remove all delimiters
    zip.gsub!(/[\,\.\-:\s]*/,'')

    parts = zip.to_s.split(re)
    parts.delete_if {|x| x == ''}
    parts.join("#{delimiter}")
  end
end

app/views/cmts/_back_to_reports.html.erb
<br />
<div class="container-fluid">
	<div class="row-fluid">
	  <div class="col-md-2">
	    <p>
		    <%= button_to 'Back to Report', report_path, :method => 'get', :class => 'btn btn-mini btn-primary' %>
	    </p>
	  </div>
	</div>
</div>

app/views/cmts/new.html.erb
<h1>New CMTS</h1>

<%= render 'form' %>
<br />
<%= link_to 'Back', cmts_path %>

app/views/cmts/report.html.erb
<style>
.div ds {
  display: inline;
}
</style>

<h2 style="text-align:center;">C3/CMTS Statistics</h2>

<div class="row">
<div class="col-md-1"></div>
<div class="col-md-10">

	<br />
	<p>
	<%= button_to 'Back to List', root_path, :method => 'get', :class => 'btn btn-mini btn-primary' %>
	</p>
</div>

	<div class="container-fluid">
  	<div class="row-fliud">
    	<div class="centering col-md-6">
				<h4><b>Site Totals</b></h4>
				<div class="panel panel-default">
					<table class="table table-striped table-bordered table-condensed table-hover">
					  <thead>
						  <tr>
						    <th>SITE</th>
						    <th>TOTAL REGISTERED</th>
						  </tr>
						</thead>
						<tbody>
							<% @totals.each do |k,v| %>
							  <tr>
							  	<td><%= k %></td>
							  	<td><%= v %></td>
							  </tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

	<% @report.sort_by {|k,v| k[:host] if k == 'host'.to_sym}.each do |cmts| %>
		<% provisioned = 0 %>
		<% idx = 0 %>
		<div class="row">
		<h3><span class="label label-primary"><%= cmts[:title] %></span></h3>
			<div class="col-md-5">
				<div class='ds'>

						<%= link_to image_tag('list.png', :height => '30', :width => '25'), showcablemodems_path(:target => "#{cmts[:host]}"), :method => :get, 'data-original-title'.to_sym => 'Show Cable Modems Listing', :class => "scm" %>

						<%= link_to image_tag('trash_empty.png', :height => '37', :width => '35'), deleteoffline_path(:target => "#{cmts[:host]}", :filter => 'all'), :confirm => 'Are you sure you want to delete offline modems?', :remote => true, :method => :get, 'data-original-title'.to_sym => 'Delete offline modems from show cable modem list', :class => "deleteoffline" %>

						<%= link_to image_tag('arrow.png', :height => '35', :width => '35'), showflaplist_path(:target => "#{cmts[:host]}"), :method => :get, 'data-original-title'.to_sym => 'Show Flapping List', :class => "flaplist" %>

						<% if cmts[:totalsubs] > 0 %>
							<%= link_to image_tag('sweep.png', :height => '30', :width => '30'), sweep_path(:target => "#{cmts[:host]}"), :method => :get, 'data-original-title'.to_sym => 'Sweep all registered modems', :class => "sweep" %>
		        <% end %>
		        <!-- Show Cable Modem Summary Link -->
						<%= link_to image_tag('sum.png', :height => '22', :width => '22'), scmsum_path(:target => "#{cmts[:host]}"), :method => :get, 'data-original-title'.to_sym => 'Show Cable Modem Summary', :class => "scmsum" %>
					</h4>
		    	</div>

			    <% if session[:admin] %>
						<div style="margin-top:30px; padding-bottom:10px; margin-left:0px;">
			    		<%= link_to 'Manage', managec3_path(:target => cmts[:host]), :method => 'get', :class => 'btn btn-mini btn-danger' %>
						</div>
				<% end %>
			</div>

			<div class="col-md-5" style="margin-top: -30px;">
	    		<% color = 'red' if cmts[:ds_util] >= 90 %>
	    		<% color = 'green' if cmts[:ds_util] < 90 %>
	    	<div class="panel panel-default">
					<table class="table table-striped table-bordered table-condensed table-hover">
					  <thead>
						  <tr>
						  	<th>FREQUENCY</th>
						  	<th>POLARITY</th>
						    <th>DS MODULATION</th>
						    <th>UTILIZATION</th>
						    <th>BANDWIDTH</th>
						  </tr>
						</thead>
						<tbody>
							<tr>
								<td><%= cmts[:ds_freq] %>Mhz</td>
								<td><%= cmts[:polarity] %></td>
								<td><%= cmts[:ds_modulation].upcase %></td>
								<td class='dsutil' style="color:<%= color %>" rel='tooltip'><%= cmts[:ds_util] %>% <div style="display:inline;"><%= link_to image_tag('ds_util_graph.jpg', :height => '22', :width => '22'), @ds_util_graph_map[cmts[:host]] %></div></td>
								<td><%= link_to image_tag('ds_graph.png', :height => '22', :width => '50'), @ds_bandwidth_graph_map[cmts[:host]] %></td>
							</tr>
						</tbody>
					</table>
				</div>
			  <% if session[:admin] %>
					<%= link_to 'Config', showrun_path(:target => "#{cmts[:host]}"), :method => :get, :class => 'btn btn-mini btn-primary' %>
					<%= link_to 'Controllers', showcontrollers_path(:target => "#{cmts[:host]}"), :method => :get, :class => 'btn btn-mini btn-primary' %>
					<%= link_to 'Environ', showenvironment_path(:target => "#{cmts[:host]}"), :method => :get, :class => 'btn btn-mini btn-primary' %>
				<% end %>
			</div>
		</div>

		<div class="panel panel-default">
			<table class="table table-striped table-condensed table-hover">
			  <thead>
				  <tr>
				    <th>CHANNEL</th>
				    <th colspan="2">STATE</th>
				    <th></th>
				    <th>PROVISIONED COUNT</th>
				    <th><%= link_to 'REGISTERED COUNT', @cpe_graph_map[cmts[:host]] %></th>
				    <th>% of PROVISIONED</th>
				    <th>% of TOTAL</th>
				    <th>UPSTREAM FREQUENCY (MHz)</th>
				    <th>CHANNEL WIDTH (kHz)</th>
				    <th>DOCSIS</th>
				    <th>UPSTREAM Modulation</th>
				    <th>UPSTREAM SNR</th>
				    <th><%= link_to 'MER', @mer_graph_map[cmts[:host]] %></th>
				    <th>UTIL</th>
				  </tr>
				</thead>
				<tbody>
					<% cmts.each do |k,v| %>
					  <% next if k == :host %>
					  <% next if k == :title %>
					  <% next if k == :totalsubs %>
	         	<% next if k == :avg_us %>
					  <% next if k == :ds_freq %>
					  <% next if k == :polarity %>
					  <% next if k == :ds_modulation %>
					  <% next if k == :ds_util %>

					  <% color = '' %>
					  <% color = 'red' if (v[:prov] > 0 && v[:subs] == 0) %>
					  <% merstyle = '' %>
					  <% merstyle = 'color:red;font-weight:bold;' if ((v[:mer] < 15) && (v[:int_state] != "ADMIN DOWN") && (v[:prov] != 0)) %>

					  <tr>
					  	<td><%= k - 1%></td>
					  	<td width='110px'><%= v[:int_state] %></td>
					  	<td>
					  	  <% state_img = ''; div_class = ''; tooltip = '' %>
					  		<% if v[:int_state] == 'ADMIN DOWN' %>
					  			<% state_img = 'down_arrow.png'; div_class = 'interface_control_up'; tooltip = 'Turn Interface Up' %>
					  		<% else %>
					  			<% state_img = 'up_arrow.png'; div_class = 'interface_control_down'; tooltip = 'Turn Interface Down' %>
					  		<% end %>
						  	<%= link_to image_tag(state_img, :height => '20', :width => '20'), showcablemodems_path(:target => "#{cmts[:host]}"), :method => :get, 'data-original-title'.to_sym => tooltip, :class => div_class %>
					  	<td/>
					  	<td><%= v[:prov] %></td>
					  	<% provisioned += v[:prov] %>
					  	<td style="color:<%= color %>"><%= v[:subs] %></td>
					  	<% tp = ((v[:subs].to_f/v[:prov])*100).finite? ? (v[:subs].to_f/v[:prov])*100 : 0.0 %>
					  	<td style="color:<%= color %>"><%= tp.round(2) %></td>
					  	<% ts = ((v[:subs].to_f/cmts[:totalsubs])*100).finite? ? (v[:subs].to_f/cmts[:totalsubs])*100 : 0.0 %>
					  	<td style="color:<%= color %>"><%= ts.round(2) %></td>

					  	<td><%= v[:freq] %></td>
					  	<td><%= v[:ch_width] %></td>
					  	<td><%= v[:ch_type] %></td>
					  	<td><%= v[:ch_modulation] %></td>
					  	<td><%= v[:snr] %></td>
					  	<td style="<%= merstyle %>"><%= v[:mer] %></td>

					  	<% color = 'red' if v[:util].to_i >= 90 %>
	    				<% color = 'green' if v[:util].to_i < 90 %>
					  	<td style="color:<%= color %>;text-align:right;"><%= v[:util] %>%</td>
					  	<% if (cmts[:totalsubs]>0) %>
								<% if v[:subs] > 0 %>
									<td><%= link_to image_tag('sweep.png', :height => '25', :width => '25'), sweep_path(:target => "#{cmts[:host]}", :channel => k.to_i - 1), :method => :get, 'data-original-title'.to_sym => 'Sweep registered modems on this channel', :class => "channelsweep" %></td>
								<% else %>
									<td></td>
								<% end %>
							<% end %>
					  </tr>
					<% end %>
					<tr style='background:#ACC0C8;font-weight:bold;'>
						<td colspan=4>Total Subs:</td>
						<td colspan=1><%= provisioned %></td>
						<td colspan=1><%= cmts[:totalsubs] %></td>
						<% total_per_of_prov = (cmts[:totalsubs].to_f / provisioned.to_f).finite? ? (cmts[:totalsubs].to_f / provisioned.to_f)*100 : 0.0 %>
	      		<td colspan=4><%= total_per_of_prov.round(2) %></td>
	        	<td colspan=2>Avg Upsream:</td>
	        	<td colspan=2><%= cmts[:avg_us].round(2) %></td>
	        	<td style="color:<%= color %>;"><%= avg_us_util(cmts) %>%</td>
	        	<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br />
	<% end %>
	<p>
		<%= button_to 'Back to List', root_path, :method => 'get', :class => 'btn btn-mini btn-primary' %>
	</p>
</div>
<div class="col-md-1"></div>
</div>

app/views/cmts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @cmt.host %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cmt.name %>
</p>

<p>
  <strong>Downstream freq:</strong>
  <%= @cmt.downstream_freq %>
</p>

<%= link_to 'Edit', edit_cmt_path(@cmt) %> |
<%= link_to 'Back', cmts_path %>