config/routes.rb
ArrisTool::Application.routes.draw do
  resources :arris_headends

	match '/report', to: 'cmts#report', via: 'get'
	match '/sweep', to: 'cmts#sweep', via: 'get'
  match '/managec3' => 'cmts#managec3', via: 'get'
	match '/showcablemodems' => 'cmts#scm', via: 'get'
  match '/scmsum' => 'cmts#scmsum', via: 'get'
	match '/scmdetail' => 'cmts#scmdetail', via: 'get'
  match '/schdetail' => 'cmts#schdetail', via: 'get'
  match '/hostmaclookup' => 'cmts#hostmaclookup', via: 'get'
  match '/showrun' => 'cmts#showrun', via: 'get'
  match '/showflaplist' => 'cmts#showflaplist', via: 'get'
	match '/showcontrollers' => 'cmts#showcontrollers', via: 'get'
  match '/showenvironment' => 'cmts#showenvironment', via: 'get'
  match '/deleteoffline' => 'cmts#deleteoffline', via: 'get'
  match '/resetmodemcounters' => 'cmts#resetmodemcounters', via: 'get'
  match '/clearflaplist' => 'cmts#clearflaplist', via: 'get'
  match '/plat' => 'cmts#showplatinfo', via: 'get'

  resources :cmts

  root :to => 'cmts#index'

end

app/models/arris_headend.rb
class ArrisHeadend < ActiveRecord::Base
end

app/controllers/arris_headends_controller.rb
class ArrisHeadendsController < ApplicationController
  # GET /arris_headends
  # GET /arris_headends.json
  def index
    @arris_headends = ArrisHeadend.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @arris_headends }
    end
  end

  # GET /arris_headends/1
  # GET /arris_headends/1.json
  def show
    @arris_headend = ArrisHeadend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @arris_headend }
    end
  end

  # GET /arris_headends/new
  # GET /arris_headends/new.json
  def new
    @arris_headend = ArrisHeadend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @arris_headend }
    end
  end

  # GET /arris_headends/1/edit
  def edit
    @arris_headend = ArrisHeadend.find(params[:id])
  end

  # POST /arris_headends
  # POST /arris_headends.json
  def create
    @arris_headend = ArrisHeadend.new(arris_headend_params)

    respond_to do |format|
      if @arris_headend.save
        format.html { redirect_to @arris_headend, notice: 'Arris headend was successfully created.' }
        format.json { render json: @arris_headend, status: :created, location: @arris_headend }
      else
        format.html { render action: "new" }
        format.json { render json: @arris_headend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arris_headends/1
  # PATCH/PUT /arris_headends/1.json
  def update
    @arris_headend = ArrisHeadend.find(params[:id])

    respond_to do |format|
      if @arris_headend.update_attributes(arris_headend_params)
        format.html { redirect_to @arris_headend, notice: 'Arris headend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @arris_headend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arris_headends/1
  # DELETE /arris_headends/1.json
  def destroy
    @arris_headend = ArrisHeadend.find(params[:id])
    @arris_headend.destroy

    respond_to do |format|
      format.html { redirect_to arris_headends_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def arris_headend_params
      params.require(:arris_headend).permit(:downstream_freq, :host, :name, :polarity)
    end
end

app/helpers/arris_headends_helper.rb
module ArrisHeadendsHelper
end

app/views/arris_headends/_form.html.erb
<%= form_for(@arris_headend) do |f| %>
  <% if @arris_headend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@arris_headend.errors.count, "error") %> prohibited this arris_headend from being saved:</h2>

      <ul>
      <% @arris_headend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :downstream_freq %><br />
    <%= f.text_field :downstream_freq %>
  </div>
  <div class="field">
    <%= f.label :polarity %><br />
    <%= f.text_field :polarity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arris_headends/edit.html.erb
<h1>Editing arris_headend</h1>

<%= render 'form' %>

<%= link_to 'Show', @arris_headend %> |
<%= link_to 'Back', arris_headends_path %>

app/views/arris_headends/index.html.erb
<h1>Listing arris_headends</h1>

<table>
  <tr>
    <th>Host</th>
    <th>Name</th>
    <th>Downstream freq</th>
    <th>Polarity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @arris_headends.each do |arris_headend| %>
  <tr>
    <td><%= arris_headend.host %></td>
    <td><%= arris_headend.name %></td>
    <td><%= arris_headend.downstream_freq %></td>
    <td><%= arris_headend.polarity %></td>
    <td><%= link_to 'Show', arris_headend %></td>
    <td><%= link_to 'Edit', edit_arris_headend_path(arris_headend) %></td>
    <td><%= link_to 'Destroy', arris_headend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Arris headend', new_arris_headend_path %>

app/views/arris_headends/new.html.erb
<h1>New arris_headend</h1>

<%= render 'form' %>

<%= link_to 'Back', arris_headends_path %>

app/views/arris_headends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Host:</b>
  <%= @arris_headend.host %>
</p>

<p>
  <b>Name:</b>
  <%= @arris_headend.name %>
</p>

<p>
  <b>Downstream freq:</b>
  <%= @arris_headend.downstream_freq %>
</p>

<p>
  <b>Polarity:</b>
  <%= @arris_headend.polarity %>
</p>


<%= link_to 'Edit', edit_arris_headend_path(@arris_headend) %> |
<%= link_to 'Back', arris_headends_path %>